# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fifo_FWFT/fifo_FWFT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_FWFT || ORIG_REF_NAME==fifo_FWFT}]

# IP: ip/fifo_standard/fifo_standard.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_standard || ORIG_REF_NAME==fifo_standard}]
