# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000

create_project -in_memory -part xc7z020clg400-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.cache/wt [current_project]
set_property parent.project_path E:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths E:/uv/fpga/verify/vry_fifofirstread/vry_fifofirstread/packageip_vry_fifofirstread [current_project]
read_ip E:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_FWFT/fifo_FWFT.xci
set_property used_in_implementation false [get_files -all e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_FWFT/fifo_FWFT/fifo_FWFT.xdc]
set_property used_in_implementation false [get_files -all e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_FWFT/fifo_FWFT_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_FWFT/fifo_FWFT.dcp]
set_property is_locked true [get_files E:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_FWFT/fifo_FWFT.xci]

read_ip E:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard.xci
set_property used_in_implementation false [get_files -all e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard/fifo_standard.xdc]
set_property used_in_implementation false [get_files -all e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard.dcp]
set_property is_locked true [get_files E:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard.xci]

read_verilog -library xil_defaultlib E:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/imports/new/vry_FifoFirstRead.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file vry_FifoFirstRead.hwdef }
synth_design -top vry_FifoFirstRead -part xc7z020clg400-2
write_checkpoint -noxdef vry_FifoFirstRead.dcp
catch { report_utilization -file vry_FifoFirstRead_utilization_synth.rpt -pb vry_FifoFirstRead_utilization_synth.pb }
