# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg400-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.cache/wt [current_project]
set_property parent.project_path E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/ip_repo/axi_full_slave2_1.0
  E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/ip_repo/axi_full_slave1_1.0
  E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/ip_repo/axi_full_slave_1.0
  E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/ip_repo/axi_full_master_1.0
} [current_project]
read_ip e:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_dma_0/axi_dma_0.xci
set_property is_locked true [get_files e:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_dma_0/axi_dma_0.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file axi_dma_0.hwdef }
synth_design -top axi_dma_0 -part xc7z020clg400-2 -mode out_of_context
rename_ref -prefix_all axi_dma_0_
write_checkpoint -noxdef axi_dma_0.dcp
catch { report_utilization -file axi_dma_0_utilization_synth.rpt -pb axi_dma_0_utilization_synth.pb }
if { [catch {
  file copy -force E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.runs/axi_dma_0_synth_1/axi_dma_0.dcp e:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_dma_0/axi_dma_0.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub e:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_dma_0/axi_dma_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub e:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_dma_0/axi_dma_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim e:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_dma_0/axi_dma_0_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim e:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_dma_0/axi_dma_0_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
