# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg400-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.cache/wt [current_project]
set_property parent.project_path E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/ip_repo/axi_full_slave2_1.0
  E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/ip_repo/axi_full_slave1_1.0
  E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/ip_repo/axi_full_slave_1.0
  E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/ip_repo/axi_full_master_1.0
} [current_project]
add_files E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib E:/UV/FPGA/VERIFY/vry_AXI_DMA_1/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file design_1_wrapper.hwdef }
synth_design -top design_1_wrapper -part xc7z020clg400-2
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
