# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/UV/FPGA/VERIFY/vry_AXI_DMA/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_cdma_0/axi_cdma_0.xci
# IP: The module: 'axi_cdma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UV/FPGA/VERIFY/vry_AXI_DMA/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_cdma_0/axi_cdma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_cdma_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/UV/FPGA/VERIFY/vry_AXI_DMA/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_cdma_0/axi_cdma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_cdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/UV/FPGA/VERIFY/vry_AXI_DMA/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_cdma_0/axi_cdma_0.xci
# IP: The module: 'axi_cdma_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UV/FPGA/VERIFY/vry_AXI_DMA/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_cdma_0/axi_cdma_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_cdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/UV/FPGA/VERIFY/vry_AXI_DMA/vry_AXI_DMA/vry_AXI_DMA.srcs/sources_1/ip/axi_cdma_0/axi_cdma_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_cdma_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
