# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000

create_project -in_memory -part xc7z020clg400-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.cache/wt [current_project]
set_property parent.project_path E:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths E:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/PackageIp_vry_FifoFirstRead1 [current_project]
add_files -quiet E:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.runs/vry_FifoFirstRead_1_synth_1/vry_FifoFirstRead_1.dcp
set_property used_in_implementation false [get_files E:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.runs/vry_FifoFirstRead_1_synth_1/vry_FifoFirstRead_1.dcp]
read_verilog -library xil_defaultlib E:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/new/vry_VivadoIp.v
catch { write_hwdef -file vry_VivadoIp.hwdef }
synth_design -top vry_VivadoIp -part xc7z020clg400-2
write_checkpoint -noxdef vry_VivadoIp.dcp
catch { report_utilization -file vry_VivadoIp_utilization_synth.rpt -pb vry_VivadoIp_utilization_synth.pb }
