# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/vry_FifoFirstRead_1.xci
# IP: The module: 'vry_FifoFirstRead_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_standard/fifo_standard.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_standard || ORIG_REF_NAME==fifo_standard}]

# IP: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_FWFT/fifo_FWFT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_FWFT || ORIG_REF_NAME==fifo_FWFT}]

# XDC: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_standard/fifo_standard/fifo_standard.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_standard || ORIG_REF_NAME==fifo_standard}] {/U0 }]/U0 ]]

# XDC: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_standard/fifo_standard_ooc.xdc

# XDC: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_FWFT/fifo_FWFT/fifo_FWFT.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_FWFT || ORIG_REF_NAME==fifo_FWFT}] {/U0 }]/U0 ]]

# XDC: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_FWFT/fifo_FWFT_ooc.xdc

# IP: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/vry_FifoFirstRead_1.xci
# IP: The module: 'vry_FifoFirstRead_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_standard/fifo_standard.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_standard || ORIG_REF_NAME==fifo_standard}]

# IP: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_FWFT/fifo_FWFT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_FWFT || ORIG_REF_NAME==fifo_FWFT}]

# XDC: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_standard/fifo_standard/fifo_standard.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_standard || ORIG_REF_NAME==fifo_standard}] {/U0 }]/U0 ]]

# XDC: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_standard/fifo_standard_ooc.xdc

# XDC: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_FWFT/fifo_FWFT/fifo_FWFT.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_FWFT || ORIG_REF_NAME==fifo_FWFT}] {/U0 }]/U0 ]]

# XDC: e:/UV/FPGA/VERIFY/vry_VivadoIp/vry_VivadoIp/vry_VivadoIp.srcs/sources_1/ip/vry_FifoFirstRead_1/src/fifo_FWFT/fifo_FWFT_ooc.xdc
