# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard.xci
# IP: The module: 'fifo_standard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard/fifo_standard.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_standard'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_standard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard.xci
# IP: The module: 'fifo_standard' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard/fifo_standard.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_standard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/UV/FPGA/VERIFY/vry_FifoFirstRead/vry_FifoFirstRead/vry_FifoFirstRead.srcs/sources_1/ip/fifo_standard/fifo_standard_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_standard'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
