# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg400-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/UV/FPGA/VERIFY/vry_Verilog/vry_Verilog/vry_Verilog.cache/wt [current_project]
set_property parent.project_path E:/UV/FPGA/VERIFY/vry_Verilog/vry_Verilog/vry_Verilog.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib E:/UV/FPGA/VERIFY/vry_Verilog/vry_Verilog/vry_Verilog.srcs/sources_1/new/vry_declare.v
catch { write_hwdef -file vry_declare.hwdef }
synth_design -top vry_declare -part xc7z020clg400-2
write_checkpoint -noxdef vry_declare.dcp
catch { report_utilization -file vry_declare_utilization_synth.rpt -pb vry_declare_utilization_synth.pb }
