# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/UV/FPGA/VERIFY/vry_BottlePrint/Prj_vivado/vry_BottlePrint.cache/wt [current_project]
set_property parent.project_path E:/UV/FPGA/VERIFY/vry_BottlePrint/Prj_vivado/vry_BottlePrint.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib E:/UV/FPGA/VERIFY/vry_BottlePrint/design/vry_BottlePrint.vhd
catch { write_hwdef -file vry_BottlePrint.hwdef }
synth_design -top vry_BottlePrint -part xc7z010clg400-1
write_checkpoint -noxdef vry_BottlePrint.dcp
catch { report_utilization -file vry_BottlePrint_utilization_synth.rpt -pb vry_BottlePrint_utilization_synth.pb }
